# Generated by Django 4.1 on 2022-08-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectlamdaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Team',
        ),
    ]
